package com.letsball.entity;

import java.util.Date;

public class TDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.D_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.D_NAMME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String dNamme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.D_TYPE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer dType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.D_ID
     *
     * @return the value of t_dictionary.D_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.D_ID
     *
     * @param dId the value for t_dictionary.D_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.D_NAMME
     *
     * @return the value of t_dictionary.D_NAMME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getdNamme() {
        return dNamme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.D_NAMME
     *
     * @param dNamme the value for t_dictionary.D_NAMME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setdNamme(String dNamme) {
        this.dNamme = dNamme == null ? null : dNamme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.D_TYPE
     *
     * @return the value of t_dictionary.D_TYPE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getdType() {
        return dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.D_TYPE
     *
     * @param dType the value for t_dictionary.D_TYPE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setdType(Integer dType) {
        this.dType = dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.INPUT_NAME
     *
     * @return the value of t_dictionary.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.INPUT_NAME
     *
     * @param inputName the value for t_dictionary.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.INPUT_DATE
     *
     * @return the value of t_dictionary.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.INPUT_DATE
     *
     * @param inputDate the value for t_dictionary.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.UPDATE_NAME
     *
     * @return the value of t_dictionary.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.UPDATE_NAME
     *
     * @param updateName the value for t_dictionary.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.UPDATE_DATE
     *
     * @return the value of t_dictionary.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.UPDATE_DATE
     *
     * @param updateDate the value for t_dictionary.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.DELSIGN
     *
     * @return the value of t_dictionary.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.DELSIGN
     *
     * @param delsign the value for t_dictionary.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setDelsign(Integer delsign) {
        this.delsign = delsign;
    }
}