package com.letsball.entity;

import java.util.Date;

public class TMatchFootballMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.MM_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer mmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.M_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.T_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.U_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.MATCH_MEMBER_POSITION
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String matchMemberPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football_member.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    private Integer delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.MM_ID
     *
     * @return the value of t_match_football_member.MM_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getMmId() {
        return mmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.MM_ID
     *
     * @param mmId the value for t_match_football_member.MM_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setMmId(Integer mmId) {
        this.mmId = mmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.M_ID
     *
     * @return the value of t_match_football_member.M_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.M_ID
     *
     * @param mId the value for t_match_football_member.M_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.T_ID
     *
     * @return the value of t_match_football_member.T_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.T_ID
     *
     * @param tId the value for t_match_football_member.T_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.U_ID
     *
     * @return the value of t_match_football_member.U_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.U_ID
     *
     * @param uId the value for t_match_football_member.U_ID
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.MATCH_MEMBER_POSITION
     *
     * @return the value of t_match_football_member.MATCH_MEMBER_POSITION
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getMatchMemberPosition() {
        return matchMemberPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.MATCH_MEMBER_POSITION
     *
     * @param matchMemberPosition the value for t_match_football_member.MATCH_MEMBER_POSITION
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setMatchMemberPosition(String matchMemberPosition) {
        this.matchMemberPosition = matchMemberPosition == null ? null : matchMemberPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.INPUT_NAME
     *
     * @return the value of t_match_football_member.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.INPUT_NAME
     *
     * @param inputName the value for t_match_football_member.INPUT_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.INPUT_DATE
     *
     * @return the value of t_match_football_member.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.INPUT_DATE
     *
     * @param inputDate the value for t_match_football_member.INPUT_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.UPDATE_NAME
     *
     * @return the value of t_match_football_member.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.UPDATE_NAME
     *
     * @param updateName the value for t_match_football_member.UPDATE_NAME
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.UPDATE_DATE
     *
     * @return the value of t_match_football_member.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.UPDATE_DATE
     *
     * @param updateDate the value for t_match_football_member.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football_member.DELSIGN
     *
     * @return the value of t_match_football_member.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public Integer getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football_member.DELSIGN
     *
     * @param delsign the value for t_match_football_member.DELSIGN
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    public void setDelsign(Integer delsign) {
        this.delsign = delsign;
    }
}