package com.letsball.entity;

import java.util.Date;

public class TMatchFootball {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.M_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Date matchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_ADDRESS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private String matchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_ORGANIZER
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchOrganizer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_KEEPER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchKeeperMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_DEFENDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchDefenderMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_MIDFIELDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchMidfielderMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_STRIKER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchStrikerMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_REFEREE_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchRefereeMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_TEAMA_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchTeamaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.MATCH_TEAMB_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer matchTeambId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.INPUT_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.INPUT_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.UPDATE_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_match_football.DELSIGN
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    private Integer delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.M_ID
     *
     * @return the value of t_match_football.M_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.M_ID
     *
     * @param mId the value for t_match_football.M_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_DATE
     *
     * @return the value of t_match_football.MATCH_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Date getMatchDate() {
        return matchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_DATE
     *
     * @param matchDate the value for t_match_football.MATCH_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchDate(Date matchDate) {
        this.matchDate = matchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_ADDRESS
     *
     * @return the value of t_match_football.MATCH_ADDRESS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public String getMatchAddress() {
        return matchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_ADDRESS
     *
     * @param matchAddress the value for t_match_football.MATCH_ADDRESS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchAddress(String matchAddress) {
        this.matchAddress = matchAddress == null ? null : matchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_ORGANIZER
     *
     * @return the value of t_match_football.MATCH_ORGANIZER
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchOrganizer() {
        return matchOrganizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_ORGANIZER
     *
     * @param matchOrganizer the value for t_match_football.MATCH_ORGANIZER
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchOrganizer(Integer matchOrganizer) {
        this.matchOrganizer = matchOrganizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_KEEPER_MEMBERS
     *
     * @return the value of t_match_football.MATCH_KEEPER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchKeeperMembers() {
        return matchKeeperMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_KEEPER_MEMBERS
     *
     * @param matchKeeperMembers the value for t_match_football.MATCH_KEEPER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchKeeperMembers(Integer matchKeeperMembers) {
        this.matchKeeperMembers = matchKeeperMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_DEFENDER_MEMBERS
     *
     * @return the value of t_match_football.MATCH_DEFENDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchDefenderMembers() {
        return matchDefenderMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_DEFENDER_MEMBERS
     *
     * @param matchDefenderMembers the value for t_match_football.MATCH_DEFENDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchDefenderMembers(Integer matchDefenderMembers) {
        this.matchDefenderMembers = matchDefenderMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_MIDFIELDER_MEMBERS
     *
     * @return the value of t_match_football.MATCH_MIDFIELDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchMidfielderMembers() {
        return matchMidfielderMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_MIDFIELDER_MEMBERS
     *
     * @param matchMidfielderMembers the value for t_match_football.MATCH_MIDFIELDER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchMidfielderMembers(Integer matchMidfielderMembers) {
        this.matchMidfielderMembers = matchMidfielderMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_STRIKER_MEMBERS
     *
     * @return the value of t_match_football.MATCH_STRIKER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchStrikerMembers() {
        return matchStrikerMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_STRIKER_MEMBERS
     *
     * @param matchStrikerMembers the value for t_match_football.MATCH_STRIKER_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchStrikerMembers(Integer matchStrikerMembers) {
        this.matchStrikerMembers = matchStrikerMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_REFEREE_MEMBERS
     *
     * @return the value of t_match_football.MATCH_REFEREE_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchRefereeMembers() {
        return matchRefereeMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_REFEREE_MEMBERS
     *
     * @param matchRefereeMembers the value for t_match_football.MATCH_REFEREE_MEMBERS
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchRefereeMembers(Integer matchRefereeMembers) {
        this.matchRefereeMembers = matchRefereeMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_TEAMA_ID
     *
     * @return the value of t_match_football.MATCH_TEAMA_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchTeamaId() {
        return matchTeamaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_TEAMA_ID
     *
     * @param matchTeamaId the value for t_match_football.MATCH_TEAMA_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchTeamaId(Integer matchTeamaId) {
        this.matchTeamaId = matchTeamaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.MATCH_TEAMB_ID
     *
     * @return the value of t_match_football.MATCH_TEAMB_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getMatchTeambId() {
        return matchTeambId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.MATCH_TEAMB_ID
     *
     * @param matchTeambId the value for t_match_football.MATCH_TEAMB_ID
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setMatchTeambId(Integer matchTeambId) {
        this.matchTeambId = matchTeambId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.INPUT_NAME
     *
     * @return the value of t_match_football.INPUT_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.INPUT_NAME
     *
     * @param inputName the value for t_match_football.INPUT_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.INPUT_DATE
     *
     * @return the value of t_match_football.INPUT_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.INPUT_DATE
     *
     * @param inputDate the value for t_match_football.INPUT_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.UPDATE_NAME
     *
     * @return the value of t_match_football.UPDATE_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.UPDATE_NAME
     *
     * @param updateName the value for t_match_football.UPDATE_NAME
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.UPDATE_DATE
     *
     * @return the value of t_match_football.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.UPDATE_DATE
     *
     * @param updateDate the value for t_match_football.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_match_football.DELSIGN
     *
     * @return the value of t_match_football.DELSIGN
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Integer getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_match_football.DELSIGN
     *
     * @param delsign the value for t_match_football.DELSIGN
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setDelsign(Integer delsign) {
        this.delsign = delsign;
    }
}