package com.letsball.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TMatchFootballExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public TMatchFootballExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMIdIsNull() {
            addCriterion("M_ID is null");
            return (Criteria) this;
        }

        public Criteria andMIdIsNotNull() {
            addCriterion("M_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMIdEqualTo(Integer value) {
            addCriterion("M_ID =", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotEqualTo(Integer value) {
            addCriterion("M_ID <>", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThan(Integer value) {
            addCriterion("M_ID >", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("M_ID >=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThan(Integer value) {
            addCriterion("M_ID <", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThanOrEqualTo(Integer value) {
            addCriterion("M_ID <=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdIn(List<Integer> values) {
            addCriterion("M_ID in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotIn(List<Integer> values) {
            addCriterion("M_ID not in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdBetween(Integer value1, Integer value2) {
            addCriterion("M_ID between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotBetween(Integer value1, Integer value2) {
            addCriterion("M_ID not between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNull() {
            addCriterion("MATCH_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNotNull() {
            addCriterion("MATCH_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMatchDateEqualTo(Date value) {
            addCriterionForJDBCDate("MATCH_DATE =", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MATCH_DATE <>", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThan(Date value) {
            addCriterionForJDBCDate("MATCH_DATE >", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MATCH_DATE >=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThan(Date value) {
            addCriterionForJDBCDate("MATCH_DATE <", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MATCH_DATE <=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateIn(List<Date> values) {
            addCriterionForJDBCDate("MATCH_DATE in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("MATCH_DATE not in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MATCH_DATE between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MATCH_DATE not between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchAddressIsNull() {
            addCriterion("MATCH_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMatchAddressIsNotNull() {
            addCriterion("MATCH_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchAddressEqualTo(String value) {
            addCriterion("MATCH_ADDRESS =", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressNotEqualTo(String value) {
            addCriterion("MATCH_ADDRESS <>", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressGreaterThan(String value) {
            addCriterion("MATCH_ADDRESS >", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MATCH_ADDRESS >=", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressLessThan(String value) {
            addCriterion("MATCH_ADDRESS <", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressLessThanOrEqualTo(String value) {
            addCriterion("MATCH_ADDRESS <=", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressLike(String value) {
            addCriterion("MATCH_ADDRESS like", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressNotLike(String value) {
            addCriterion("MATCH_ADDRESS not like", value, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressIn(List<String> values) {
            addCriterion("MATCH_ADDRESS in", values, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressNotIn(List<String> values) {
            addCriterion("MATCH_ADDRESS not in", values, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressBetween(String value1, String value2) {
            addCriterion("MATCH_ADDRESS between", value1, value2, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchAddressNotBetween(String value1, String value2) {
            addCriterion("MATCH_ADDRESS not between", value1, value2, "matchAddress");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerIsNull() {
            addCriterion("MATCH_ORGANIZER is null");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerIsNotNull() {
            addCriterion("MATCH_ORGANIZER is not null");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerEqualTo(Integer value) {
            addCriterion("MATCH_ORGANIZER =", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerNotEqualTo(Integer value) {
            addCriterion("MATCH_ORGANIZER <>", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerGreaterThan(Integer value) {
            addCriterion("MATCH_ORGANIZER >", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_ORGANIZER >=", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerLessThan(Integer value) {
            addCriterion("MATCH_ORGANIZER <", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_ORGANIZER <=", value, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerIn(List<Integer> values) {
            addCriterion("MATCH_ORGANIZER in", values, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerNotIn(List<Integer> values) {
            addCriterion("MATCH_ORGANIZER not in", values, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_ORGANIZER between", value1, value2, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchOrganizerNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_ORGANIZER not between", value1, value2, "matchOrganizer");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersIsNull() {
            addCriterion("MATCH_KEEPER_MEMBERS is null");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersIsNotNull() {
            addCriterion("MATCH_KEEPER_MEMBERS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersEqualTo(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS =", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersNotEqualTo(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS <>", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersGreaterThan(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS >", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS >=", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersLessThan(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS <", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_KEEPER_MEMBERS <=", value, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersIn(List<Integer> values) {
            addCriterion("MATCH_KEEPER_MEMBERS in", values, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersNotIn(List<Integer> values) {
            addCriterion("MATCH_KEEPER_MEMBERS not in", values, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_KEEPER_MEMBERS between", value1, value2, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchKeeperMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_KEEPER_MEMBERS not between", value1, value2, "matchKeeperMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersIsNull() {
            addCriterion("MATCH_DEFENDER_MEMBERS is null");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersIsNotNull() {
            addCriterion("MATCH_DEFENDER_MEMBERS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersEqualTo(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS =", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersNotEqualTo(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS <>", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersGreaterThan(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS >", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS >=", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersLessThan(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS <", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_DEFENDER_MEMBERS <=", value, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersIn(List<Integer> values) {
            addCriterion("MATCH_DEFENDER_MEMBERS in", values, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersNotIn(List<Integer> values) {
            addCriterion("MATCH_DEFENDER_MEMBERS not in", values, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_DEFENDER_MEMBERS between", value1, value2, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchDefenderMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_DEFENDER_MEMBERS not between", value1, value2, "matchDefenderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersIsNull() {
            addCriterion("MATCH_MIDFIELDER_MEMBERS is null");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersIsNotNull() {
            addCriterion("MATCH_MIDFIELDER_MEMBERS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersEqualTo(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS =", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersNotEqualTo(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS <>", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersGreaterThan(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS >", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS >=", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersLessThan(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS <", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS <=", value, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersIn(List<Integer> values) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS in", values, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersNotIn(List<Integer> values) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS not in", values, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS between", value1, value2, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchMidfielderMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_MIDFIELDER_MEMBERS not between", value1, value2, "matchMidfielderMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersIsNull() {
            addCriterion("MATCH_STRIKER_MEMBERS is null");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersIsNotNull() {
            addCriterion("MATCH_STRIKER_MEMBERS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersEqualTo(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS =", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersNotEqualTo(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS <>", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersGreaterThan(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS >", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS >=", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersLessThan(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS <", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_STRIKER_MEMBERS <=", value, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersIn(List<Integer> values) {
            addCriterion("MATCH_STRIKER_MEMBERS in", values, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersNotIn(List<Integer> values) {
            addCriterion("MATCH_STRIKER_MEMBERS not in", values, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_STRIKER_MEMBERS between", value1, value2, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchStrikerMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_STRIKER_MEMBERS not between", value1, value2, "matchStrikerMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersIsNull() {
            addCriterion("MATCH_REFEREE_MEMBERS is null");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersIsNotNull() {
            addCriterion("MATCH_REFEREE_MEMBERS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersEqualTo(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS =", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersNotEqualTo(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS <>", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersGreaterThan(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS >", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS >=", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersLessThan(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS <", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_REFEREE_MEMBERS <=", value, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersIn(List<Integer> values) {
            addCriterion("MATCH_REFEREE_MEMBERS in", values, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersNotIn(List<Integer> values) {
            addCriterion("MATCH_REFEREE_MEMBERS not in", values, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_REFEREE_MEMBERS between", value1, value2, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchRefereeMembersNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_REFEREE_MEMBERS not between", value1, value2, "matchRefereeMembers");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdIsNull() {
            addCriterion("MATCH_TEAMA_ID is null");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdIsNotNull() {
            addCriterion("MATCH_TEAMA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdEqualTo(Integer value) {
            addCriterion("MATCH_TEAMA_ID =", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdNotEqualTo(Integer value) {
            addCriterion("MATCH_TEAMA_ID <>", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdGreaterThan(Integer value) {
            addCriterion("MATCH_TEAMA_ID >", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_TEAMA_ID >=", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdLessThan(Integer value) {
            addCriterion("MATCH_TEAMA_ID <", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_TEAMA_ID <=", value, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdIn(List<Integer> values) {
            addCriterion("MATCH_TEAMA_ID in", values, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdNotIn(List<Integer> values) {
            addCriterion("MATCH_TEAMA_ID not in", values, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_TEAMA_ID between", value1, value2, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeamaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_TEAMA_ID not between", value1, value2, "matchTeamaId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdIsNull() {
            addCriterion("MATCH_TEAMB_ID is null");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdIsNotNull() {
            addCriterion("MATCH_TEAMB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdEqualTo(Integer value) {
            addCriterion("MATCH_TEAMB_ID =", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdNotEqualTo(Integer value) {
            addCriterion("MATCH_TEAMB_ID <>", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdGreaterThan(Integer value) {
            addCriterion("MATCH_TEAMB_ID >", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_TEAMB_ID >=", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdLessThan(Integer value) {
            addCriterion("MATCH_TEAMB_ID <", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_TEAMB_ID <=", value, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdIn(List<Integer> values) {
            addCriterion("MATCH_TEAMB_ID in", values, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdNotIn(List<Integer> values) {
            addCriterion("MATCH_TEAMB_ID not in", values, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_TEAMB_ID between", value1, value2, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andMatchTeambIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_TEAMB_ID not between", value1, value2, "matchTeambId");
            return (Criteria) this;
        }

        public Criteria andInputNameIsNull() {
            addCriterion("INPUT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andInputNameIsNotNull() {
            addCriterion("INPUT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andInputNameEqualTo(String value) {
            addCriterion("INPUT_NAME =", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameNotEqualTo(String value) {
            addCriterion("INPUT_NAME <>", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameGreaterThan(String value) {
            addCriterion("INPUT_NAME >", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameGreaterThanOrEqualTo(String value) {
            addCriterion("INPUT_NAME >=", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameLessThan(String value) {
            addCriterion("INPUT_NAME <", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameLessThanOrEqualTo(String value) {
            addCriterion("INPUT_NAME <=", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameLike(String value) {
            addCriterion("INPUT_NAME like", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameNotLike(String value) {
            addCriterion("INPUT_NAME not like", value, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameIn(List<String> values) {
            addCriterion("INPUT_NAME in", values, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameNotIn(List<String> values) {
            addCriterion("INPUT_NAME not in", values, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameBetween(String value1, String value2) {
            addCriterion("INPUT_NAME between", value1, value2, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputNameNotBetween(String value1, String value2) {
            addCriterion("INPUT_NAME not between", value1, value2, "inputName");
            return (Criteria) this;
        }

        public Criteria andInputDateIsNull() {
            addCriterion("INPUT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInputDateIsNotNull() {
            addCriterion("INPUT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInputDateEqualTo(Date value) {
            addCriterionForJDBCDate("INPUT_DATE =", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("INPUT_DATE <>", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateGreaterThan(Date value) {
            addCriterionForJDBCDate("INPUT_DATE >", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("INPUT_DATE >=", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateLessThan(Date value) {
            addCriterionForJDBCDate("INPUT_DATE <", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("INPUT_DATE <=", value, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateIn(List<Date> values) {
            addCriterionForJDBCDate("INPUT_DATE in", values, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("INPUT_DATE not in", values, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("INPUT_DATE between", value1, value2, "inputDate");
            return (Criteria) this;
        }

        public Criteria andInputDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("INPUT_DATE not between", value1, value2, "inputDate");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("UPDATE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("UPDATE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("UPDATE_NAME =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("UPDATE_NAME <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("UPDATE_NAME >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_NAME >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("UPDATE_NAME <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_NAME <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("UPDATE_NAME like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("UPDATE_NAME not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("UPDATE_NAME in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("UPDATE_NAME not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("UPDATE_NAME between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("UPDATE_NAME not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDelsignIsNull() {
            addCriterion("DELSIGN is null");
            return (Criteria) this;
        }

        public Criteria andDelsignIsNotNull() {
            addCriterion("DELSIGN is not null");
            return (Criteria) this;
        }

        public Criteria andDelsignEqualTo(Integer value) {
            addCriterion("DELSIGN =", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignNotEqualTo(Integer value) {
            addCriterion("DELSIGN <>", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignGreaterThan(Integer value) {
            addCriterion("DELSIGN >", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELSIGN >=", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignLessThan(Integer value) {
            addCriterion("DELSIGN <", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignLessThanOrEqualTo(Integer value) {
            addCriterion("DELSIGN <=", value, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignIn(List<Integer> values) {
            addCriterion("DELSIGN in", values, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignNotIn(List<Integer> values) {
            addCriterion("DELSIGN not in", values, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignBetween(Integer value1, Integer value2) {
            addCriterion("DELSIGN between", value1, value2, "delsign");
            return (Criteria) this;
        }

        public Criteria andDelsignNotBetween(Integer value1, Integer value2) {
            addCriterion("DELSIGN not between", value1, value2, "delsign");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match_football
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 14 18:33:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match_football
     *
     * @mbggenerated Wed Oct 14 18:33:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}