package com.letsball.entity;

import java.util.Date;

public class TTeamFootball {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TID
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TEAM_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TEAM_CITY
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private String teamCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TEAM_CREATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Date teamCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TEAM_CAPTAIN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Long teamCaptain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.TEAM_POINTS
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Long teamPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.INPUT_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.INPUT_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.UPDATE_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.UPDATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TEAM_FOOTBALL.DELSIGN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    private Short delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TID
     *
     * @return the value of T_TEAM_FOOTBALL.TID
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TID
     *
     * @param tid the value for T_TEAM_FOOTBALL.TID
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TEAM_NAME
     *
     * @return the value of T_TEAM_FOOTBALL.TEAM_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TEAM_NAME
     *
     * @param teamName the value for T_TEAM_FOOTBALL.TEAM_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TEAM_CITY
     *
     * @return the value of T_TEAM_FOOTBALL.TEAM_CITY
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public String getTeamCity() {
        return teamCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TEAM_CITY
     *
     * @param teamCity the value for T_TEAM_FOOTBALL.TEAM_CITY
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTeamCity(String teamCity) {
        this.teamCity = teamCity == null ? null : teamCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TEAM_CREATE_DATE
     *
     * @return the value of T_TEAM_FOOTBALL.TEAM_CREATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Date getTeamCreateDate() {
        return teamCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TEAM_CREATE_DATE
     *
     * @param teamCreateDate the value for T_TEAM_FOOTBALL.TEAM_CREATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTeamCreateDate(Date teamCreateDate) {
        this.teamCreateDate = teamCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TEAM_CAPTAIN
     *
     * @return the value of T_TEAM_FOOTBALL.TEAM_CAPTAIN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Long getTeamCaptain() {
        return teamCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TEAM_CAPTAIN
     *
     * @param teamCaptain the value for T_TEAM_FOOTBALL.TEAM_CAPTAIN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTeamCaptain(Long teamCaptain) {
        this.teamCaptain = teamCaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.TEAM_POINTS
     *
     * @return the value of T_TEAM_FOOTBALL.TEAM_POINTS
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Long getTeamPoints() {
        return teamPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.TEAM_POINTS
     *
     * @param teamPoints the value for T_TEAM_FOOTBALL.TEAM_POINTS
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setTeamPoints(Long teamPoints) {
        this.teamPoints = teamPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.INPUT_NAME
     *
     * @return the value of T_TEAM_FOOTBALL.INPUT_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.INPUT_NAME
     *
     * @param inputName the value for T_TEAM_FOOTBALL.INPUT_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.INPUT_DATE
     *
     * @return the value of T_TEAM_FOOTBALL.INPUT_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.INPUT_DATE
     *
     * @param inputDate the value for T_TEAM_FOOTBALL.INPUT_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.UPDATE_NAME
     *
     * @return the value of T_TEAM_FOOTBALL.UPDATE_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.UPDATE_NAME
     *
     * @param updateName the value for T_TEAM_FOOTBALL.UPDATE_NAME
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.UPDATE_DATE
     *
     * @return the value of T_TEAM_FOOTBALL.UPDATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.UPDATE_DATE
     *
     * @param updateDate the value for T_TEAM_FOOTBALL.UPDATE_DATE
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TEAM_FOOTBALL.DELSIGN
     *
     * @return the value of T_TEAM_FOOTBALL.DELSIGN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public Short getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TEAM_FOOTBALL.DELSIGN
     *
     * @param delsign the value for T_TEAM_FOOTBALL.DELSIGN
     *
     * @mbggenerated Sat Oct 10 18:57:16 CST 2015
     */
    public void setDelsign(Short delsign) {
        this.delsign = delsign;
    }
}