package com.letsball.entity;

import java.util.Date;

public class TTeamFootballMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.TM_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Long tmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.T_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Long tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.U_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.MEMBER_POSITION
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private String memberPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.MEMBER_JOIN_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Date memberJoinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.MEMBER_LEFT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Date memberLeftDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.MEMBER_ABSENT_TIME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Long memberAbsentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.MEMBER_ABSENT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Date memberAbsentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.INPUT_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.INPUT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_football_member.DELSIGN
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    private Short delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.TM_ID
     *
     * @return the value of t_team_football_member.TM_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.TM_ID
     *
     * @param tmId the value for t_team_football_member.TM_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.T_ID
     *
     * @return the value of t_team_football_member.T_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Long gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.T_ID
     *
     * @param tId the value for t_team_football_member.T_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void settId(Long tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.U_ID
     *
     * @return the value of t_team_football_member.U_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.U_ID
     *
     * @param uId the value for t_team_football_member.U_ID
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.MEMBER_POSITION
     *
     * @return the value of t_team_football_member.MEMBER_POSITION
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public String getMemberPosition() {
        return memberPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.MEMBER_POSITION
     *
     * @param memberPosition the value for t_team_football_member.MEMBER_POSITION
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setMemberPosition(String memberPosition) {
        this.memberPosition = memberPosition == null ? null : memberPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.MEMBER_JOIN_DATE
     *
     * @return the value of t_team_football_member.MEMBER_JOIN_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Date getMemberJoinDate() {
        return memberJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.MEMBER_JOIN_DATE
     *
     * @param memberJoinDate the value for t_team_football_member.MEMBER_JOIN_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setMemberJoinDate(Date memberJoinDate) {
        this.memberJoinDate = memberJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.MEMBER_LEFT_DATE
     *
     * @return the value of t_team_football_member.MEMBER_LEFT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Date getMemberLeftDate() {
        return memberLeftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.MEMBER_LEFT_DATE
     *
     * @param memberLeftDate the value for t_team_football_member.MEMBER_LEFT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setMemberLeftDate(Date memberLeftDate) {
        this.memberLeftDate = memberLeftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.MEMBER_ABSENT_TIME
     *
     * @return the value of t_team_football_member.MEMBER_ABSENT_TIME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Long getMemberAbsentTime() {
        return memberAbsentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.MEMBER_ABSENT_TIME
     *
     * @param memberAbsentTime the value for t_team_football_member.MEMBER_ABSENT_TIME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setMemberAbsentTime(Long memberAbsentTime) {
        this.memberAbsentTime = memberAbsentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.MEMBER_ABSENT_DATE
     *
     * @return the value of t_team_football_member.MEMBER_ABSENT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Date getMemberAbsentDate() {
        return memberAbsentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.MEMBER_ABSENT_DATE
     *
     * @param memberAbsentDate the value for t_team_football_member.MEMBER_ABSENT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setMemberAbsentDate(Date memberAbsentDate) {
        this.memberAbsentDate = memberAbsentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.INPUT_NAME
     *
     * @return the value of t_team_football_member.INPUT_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.INPUT_NAME
     *
     * @param inputName the value for t_team_football_member.INPUT_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.INPUT_DATE
     *
     * @return the value of t_team_football_member.INPUT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.INPUT_DATE
     *
     * @param inputDate the value for t_team_football_member.INPUT_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.UPDATE_NAME
     *
     * @return the value of t_team_football_member.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.UPDATE_NAME
     *
     * @param updateName the value for t_team_football_member.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.UPDATE_DATE
     *
     * @return the value of t_team_football_member.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.UPDATE_DATE
     *
     * @param updateDate the value for t_team_football_member.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_football_member.DELSIGN
     *
     * @return the value of t_team_football_member.DELSIGN
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public Short getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_football_member.DELSIGN
     *
     * @param delsign the value for t_team_football_member.DELSIGN
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    public void setDelsign(Short delsign) {
        this.delsign = delsign;
    }
}