package com.letsball.entity;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_PASSWORD
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NICK_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ENG_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USEX
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String usex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SPORTS_AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private Integer sportsAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ACTIVITY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private Integer activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.BRIEF
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PROPERTY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.STATUS
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.INPUT_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.INPUT_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DELSIGN
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    private Integer delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ID
     *
     * @return the value of t_user.ID
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ID
     *
     * @param id the value for t_user.ID
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_NAME
     *
     * @return the value of t_user.LOGIN_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_NAME
     *
     * @param loginName the value for t_user.LOGIN_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_PASSWORD
     *
     * @return the value of t_user.LOGIN_PASSWORD
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_PASSWORD
     *
     * @param loginPassword the value for t_user.LOGIN_PASSWORD
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USER_NAME
     *
     * @return the value of t_user.USER_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USER_NAME
     *
     * @param userName the value for t_user.USER_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.NICK_NAME
     *
     * @return the value of t_user.NICK_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.NICK_NAME
     *
     * @param nickName the value for t_user.NICK_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ENG_NAME
     *
     * @return the value of t_user.ENG_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ENG_NAME
     *
     * @param engName the value for t_user.ENG_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USEX
     *
     * @return the value of t_user.USEX
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USEX
     *
     * @param usex the value for t_user.USEX
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setUsex(String usex) {
        this.usex = usex == null ? null : usex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.AGE
     *
     * @return the value of t_user.AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.AGE
     *
     * @param age the value for t_user.AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SPORTS_AGE
     *
     * @return the value of t_user.SPORTS_AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public Integer getSportsAge() {
        return sportsAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SPORTS_AGE
     *
     * @param sportsAge the value for t_user.SPORTS_AGE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setSportsAge(Integer sportsAge) {
        this.sportsAge = sportsAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ACTIVITY
     *
     * @return the value of t_user.ACTIVITY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public Integer getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ACTIVITY
     *
     * @param activity the value for t_user.ACTIVITY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setActivity(Integer activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.BRIEF
     *
     * @return the value of t_user.BRIEF
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.BRIEF
     *
     * @param brief the value for t_user.BRIEF
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PROPERTY
     *
     * @return the value of t_user.PROPERTY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PROPERTY
     *
     * @param property the value for t_user.PROPERTY
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.STATUS
     *
     * @return the value of t_user.STATUS
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.STATUS
     *
     * @param status the value for t_user.STATUS
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.INPUT_NAME
     *
     * @return the value of t_user.INPUT_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.INPUT_NAME
     *
     * @param inputName the value for t_user.INPUT_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.INPUT_DATE
     *
     * @return the value of t_user.INPUT_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.INPUT_DATE
     *
     * @param inputDate the value for t_user.INPUT_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UPDATE_NAME
     *
     * @return the value of t_user.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UPDATE_NAME
     *
     * @param updateName the value for t_user.UPDATE_NAME
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UPDATE_DATE
     *
     * @return the value of t_user.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UPDATE_DATE
     *
     * @param updateDate the value for t_user.UPDATE_DATE
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DELSIGN
     *
     * @return the value of t_user.DELSIGN
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public Integer getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DELSIGN
     *
     * @param delsign the value for t_user.DELSIGN
     *
     * @mbggenerated Mon Oct 26 19:41:14 CST 2015
     */
    public void setDelsign(Integer delsign) {
        this.delsign = delsign;
    }
}