package com.letsball.dao;

import com.letsball.entity.TDictionary;
import com.letsball.entity.TDictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int countByExample(TDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int deleteByExample(TDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int insert(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int insertSelective(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    List<TDictionary> selectByExample(TDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    TDictionary selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") TDictionary record, @Param("example") TDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int updateByExample(@Param("record") TDictionary record, @Param("example") TDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int updateByPrimaryKeySelective(TDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated Tue Oct 13 13:07:36 CST 2015
     */
    int updateByPrimaryKey(TDictionary record);
}