package com.letsball.dao;

import com.letsball.entity.TMatchFootball;
import com.letsball.entity.TMatchFootballExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMatchFootballMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int countByExample(TMatchFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int deleteByExample(TMatchFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int deleteByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int insert(TMatchFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int insertSelective(TMatchFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    List<TMatchFootball> selectByExample(TMatchFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    TMatchFootball selectByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") TMatchFootball record, @Param("example") TMatchFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByExample(@Param("record") TMatchFootball record, @Param("example") TMatchFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByPrimaryKeySelective(TMatchFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match_football
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByPrimaryKey(TMatchFootball record);
}