package com.letsball.dao;

import com.letsball.entity.TTeamFootball;
import com.letsball.entity.TTeamFootballExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTeamFootballMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int countByExample(TTeamFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int deleteByExample(TTeamFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int insert(TTeamFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int insertSelective(TTeamFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    List<TTeamFootball> selectByExample(TTeamFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    TTeamFootball selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TTeamFootball record, @Param("example") TTeamFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int updateByExample(@Param("record") TTeamFootball record, @Param("example") TTeamFootballExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int updateByPrimaryKeySelective(TTeamFootball record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football
     *
     * @mbggenerated Wed Oct 21 21:16:33 CST 2015
     */
    int updateByPrimaryKey(TTeamFootball record);
}