package com.letsball.dao;

import com.letsball.entity.TTeamFootballMember;
import com.letsball.entity.TTeamFootballMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTeamFootballMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int countByExample(TTeamFootballMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int deleteByExample(TTeamFootballMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int deleteByPrimaryKey(Long tmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int insert(TTeamFootballMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int insertSelective(TTeamFootballMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    List<TTeamFootballMember> selectByExample(TTeamFootballMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    TTeamFootballMember selectByPrimaryKey(Long tmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") TTeamFootballMember record, @Param("example") TTeamFootballMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByExample(@Param("record") TTeamFootballMember record, @Param("example") TTeamFootballMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByPrimaryKeySelective(TTeamFootballMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_football_member
     *
     * @mbggenerated Mon Oct 12 20:40:44 CST 2015
     */
    int updateByPrimaryKey(TTeamFootballMember record);
}